#cloud-config
hostname: slave01
fqdn: slave01
manage_etc_hosts: true
runcmd:
  - add-apt-repository ppa:webupd8team/java -y
  - echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
  - echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections
  - apt-get update
  - apt-get install oracle-java8-installer nfs-common -y
  - mkdir /jenkins
  - chown ubuntu /jenkins/
